### ISSUE TITLE
Error when Installing

### ISSUE THREAD

**Issue by MetallicDoritos** [jmobley0429/chunk_slicer#1]
![image](https://user-images.githubusercontent.com/124914025/217891310-70db04fe-0b5a-46a3-92e3-2574e953d6cd.png)
Even after downloading "My Pie Menus" repository from your profile, it does not fix the issue. I am unsure of what to do from here (also, I have no programming knowledge)

**Comment by jmobley0429** [comment]
Sorry, that was an outdated import. it should work as a standalone now.
